//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delight.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delight.Localization.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copyright Team Delight, ALL Right Reserved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoWindow_Copyright {
            get {
                return ResourceManager.GetString("InfoWindow_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delight Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoWindow_title {
            get {
                return ResourceManager.GetString("InfoWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoWindow_Version {
            get {
                return ResourceManager.GetString("InfoWindow_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View License과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoWindow_ViewLicense {
            get {
                return ResourceManager.GetString("InfoWindow_ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English (en-US)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiEdit {
            get {
                return ResourceManager.GetString("MiEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(_X)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiExit {
            get {
                return ResourceManager.GetString("MiExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export(_E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiExport {
            get {
                return ResourceManager.GetString("MiExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiFile {
            get {
                return ResourceManager.GetString("MiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiHelp {
            get {
                return ResourceManager.GetString("MiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Help(_V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiHelpView {
            get {
                return ResourceManager.GetString("MiHelpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Peripheral Device Manage(_M)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiManageDevice {
            get {
                return ResourceManager.GetString("MiManageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stage Screen Manage(_S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiManageStage {
            get {
                return ResourceManager.GetString("MiManageStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template Management(_T)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiManageTemplate {
            get {
                return ResourceManager.GetString("MiManageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project(_H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiNewProject {
            get {
                return ResourceManager.GetString("MiNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiNone {
            get {
                return ResourceManager.GetString("MiNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(_O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiOpen {
            get {
                return ResourceManager.GetString("MiOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options(_O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiOptions {
            get {
                return ResourceManager.GetString("MiOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project(_P)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiProject {
            get {
                return ResourceManager.GetString("MiProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently used Media Files(_F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiRecentMedia {
            get {
                return ResourceManager.GetString("MiRecentMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently used Project Files(_J)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiRecentProject {
            get {
                return ResourceManager.GetString("MiRecentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo(_R)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiRedo {
            get {
                return ResourceManager.GetString("MiRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(_S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiSave {
            get {
                return ResourceManager.GetString("MiSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As(_A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiSaveAs {
            get {
                return ResourceManager.GetString("MiSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools(_T)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiTools {
            get {
                return ResourceManager.GetString("MiTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Tutorial(_T)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiTutorialView {
            get {
                return ResourceManager.GetString("MiTutorialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo(_U)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiUndo {
            get {
                return ResourceManager.GetString("MiUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Delight(_A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MiViewInfo {
            get {
                return ResourceManager.GetString("MiViewInfo", resourceCulture);
            }
        }
    }
}
