//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delight.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindowText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowText() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delight.Localization.WindowText", typeof(WindowText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This library is licensed under the license Ms-PL and LGPL from FFMpeg.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FFMeLicense {
            get {
                return ResourceManager.GetString("FFMeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFMediaElement Library과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FFMeName {
            get {
                return ResourceManager.GetString("FFMeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This library is licensed under the license LGPL.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FFMpegLicense {
            get {
                return ResourceManager.GetString("FFMpegLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFMpeg Library과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FFMpegName {
            get {
                return ResourceManager.GetString("FFMpegName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Info1_content {
            get {
                return ResourceManager.GetString("Info1_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Info1_header {
            get {
                return ResourceManager.GetString("Info1_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used Library/License과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoWindow_1 {
            get {
                return ResourceManager.GetString("InfoWindow_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This library is licensed under the license LGPL.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NRecoLicense {
            get {
                return ResourceManager.GetString("NRecoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NReco Library과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NRecoName {
            get {
                return ResourceManager.GetString("NRecoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item_List1 {
            get {
                return ResourceManager.GetString("UI_Item_List1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item_List2 {
            get {
                return ResourceManager.GetString("UI_Item_List2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item_List3 {
            get {
                return ResourceManager.GetString("UI_Item_List3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item_List4 {
            get {
                return ResourceManager.GetString("UI_Item_List4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item_List5 {
            get {
                return ResourceManager.GetString("UI_Item_List5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item_List6 {
            get {
                return ResourceManager.GetString("UI_Item_List6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item1 {
            get {
                return ResourceManager.GetString("UI_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag the elements and place them on the timeline.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_Item2 {
            get {
                return ResourceManager.GetString("UI_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Item Added.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_NoItem {
            get {
                return ResourceManager.GetString("UI_NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_preview1 {
            get {
                return ResourceManager.GetString("UI_preview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visualizing Screen Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_preview2 {
            get {
                return ResourceManager.GetString("UI_preview2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stage 3D Live Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UI_preview3 {
            get {
                return ResourceManager.GetString("UI_preview3", resourceCulture);
            }
        }
    }
}
